[project]
name = "code2md"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pathspec>=0.12.1",
    "pip>=25.0.1",
    "pyperclip>=1.9.0",
]
